import os
import platform as os_platform



env = SConscript('../godot_cpp/SConstruct')
env.Append(CPPPATH=['src'])

num_jobs = ARGUMENTS.get('jobs', 4)
platform = ARGUMENTS.get('platform', 'linux')

env.Append(LIBS=[
	'avcodec', 
	'avformat', 
	'avfilter', 
	'avdevice', 
	'avutil', 
	'swscale', 
	'swresample'])


if platform == 'windows':
	folder_ffmpeg_bin = os.path.join(
		os.path.dirname(os.path.realpath('__file__')), 'ffmpeg_bin')
	os.makedirs(folder_ffmpeg_bin, exist_ok=True)

	# Building FFmpeg
	config_extra_args = ''
	if os_platform.system().lower() == 'linux':
		os.environ['PATH'] = '/opt/bin/' + os.environ['PATH']
		config_extra_args = f'--cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32'

	os.chdir('ffmpeg')
	os.system(f'./configure --prefix={folder_ffmpeg_bin} --enable-gpl --enable-shared {config_extra_args}')
	os.system(f'make -j {num_jobs}')
	os.system(f'make -j {num_jobs} install')
	os.chdir('..')

	if os_platform.system().lower() == 'windows':
		env.Append(LIBS = [
			'avcodec.lib', 
			'avformat.lib', 
			'avfilter.lib', 
			'avdevice.lib', 
			'avutil.lib', 
			'swscale.lib', 
			'swresample.lib'])
	
	env.Append(CPPPATH = ['ffmpeg_bin/include'])
	env.Append(LIBPATH = ['ffmpeg_bin/bin'])


src = Glob('src/*.cpp')
libpath = 'libgozen{}{}'.format(env['suffix'], env['SHLIBSUFFIX'])
sharedlib = env.SharedLibrary(libpath, src, CPPFLAGS=['-g'])

Default(sharedlib)
